[package]
name = "piconsole"
version = "0.1.0"
authors = ["Alex Habich <me@alexnader.dev>"]
edition = "2018"


[dependencies]
picore = { path = "../picore" }
pancurses = "0.16.1"
itertools = "0.10.0"
