[package]
name = "picore"
version = "0.1.0"
authors = ["Alex Habich <me@alexnader.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
itertools = "0.10.0"
